# Generated by Django 5.2.8 on 2025-11-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_quizattempt_unlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelunlock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante'), ('ADMIN', 'Administrador')], default='ESTUDIANTE', max_length=20, verbose_name='Rol de Usuario'),
        ),
    ]
